# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33c0e70c1c81a33fde0d185bd21ec24d3aa801fba82f5158f408b91f99f973a7a14faea42b6ff15202e2a17d79deb4291ffda364e2442ddfc1f2709e6a8abde9
  facebook_app_id: 1508436292776280
  facebook_app_secret: df3796251e79956c82bbe8f4a9532f80
  vkontakte_app_id: 4607690
  vkontakte_app_secret: MivbFyoQpGw9RLvChe4a
  twitter_app_id: mUTdvl8KuupEIXjvYAOOqo6sJ
  twitter_app_secret: nnqm0AdPxyhxsW8eybWi1JuC8nZhdHCb7daAmGTJdG6CCAs0ht

test:
  secret_key_base: 3f425eea6c8a8c1c9666ffa3eebbdeb859ba4296547802448776b1ae0e68d59639dfc568d54a4b74abc68816208b017d18d9db8fe754f6a6610bbb4b57efa851

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
  vkontakte_app_id: <%= ENV["VKONTAKTE_APP_SECRET"] %>
  vkontakte_app_secret: <%= ENV["VKONTAKTE_APP_SECRET"] %>
  twitter_app_id: <%= ENV["TWITTER_APP_ID"] %>
  twitter_app_secret: <%= ENV["TWITTER_APP_ID"] %>