production:
  pid_file: /home/deployer/qna/shared/tmp/pids/searchd.pid
  indices_locaiton: /home/deployer/qna/shared/db/sphinx
  configuration_file: /home/deployer/qna/shared/production.sphinx.conf
  binlog_path: /home/deployer/qna/shared/binlog